.ad l
.TH pkgstatus 1 "April 27, 1999"
.SH NAME
.HP 10
.B pkgstatus
\- Query cvs for status of files.

.SH SYNOPSIS
.HP 10
.B pkgstatus
.B [-?, --help]
.B [-m, --only-modified]

.SH DESCRIPTION
pkgstatus queries cvs for each file in the
distribution. It may be slow for remote servers.

.SH OPTIONS
.B -?, --help
.RS 8
 Prints the usage message.
.RE

.PP
.B -m, --only-modified
.RS 8
 Only show modified files.
.RE

.SH AUTHOR
James Amundson. (amundson@fnal.gov)


