#!/bin/sh
#
#  Test out the srt_ntlib command
#

CMD="python srt_ntlib.py"
unset IDE_DUMP

echo Dump the commands we would have executed
$CMD -NTNoRun r libstuff.a junk.o

echo
echo Make sure that SRT directory stuff gets through!
$CMD -NTNoRun r /usr/products/libstuff.a /usr/products/junk.o